# ==============
# Default Values
# ==============
repository: https://repos.fedorapeople.org/repos/pulp/pulp/stable/2/
keypair_name: pulp-ci-key
private_key: id_rsa
distribution: el6.6
flavor: m1.small
security_group: pulp
cloud_config: cloud-init/cloud-config.txt


# ==================
# Instance Structure
# ==================
structure:
    instance_name: jenkins-el6-pulp-server
    role: server
    flavor: m1.medium
    children:
        - instance_name: jenkins-el6-pulp-consumer
          role: consumer


# =========================
# Integration Test Instance
# =========================
pulp_tester:
    distribution: fc20
    instance_name: jenkins-el6-pulp-tester
    role: tester
    os_name: Fedora
    os_version: 20
    tests_destination: test/el6.xml
    test_suite_branch: pulp-2.4
