# This is a sample configuration file for deploying an environment. You can make
# more than one of these configuration files and pass them all to the
# 'deploy-environment.py' script. They will be overlayed in the order they are
# passed in, so the last configuration file will override any duplicate option
# found in any of the previous configuration files.
#
# Any key-value pair specified that is not one of the expected dictionaries is
# treated as a default value and applied to the instances if they are missing
# that value. Here, we define some default parameters for the instances. If
# you want an instance to have a special value for any of these keys, specify
# it in the instance declaration.


# ==============
# Default Values 
# ==============

# Specify the repository to add to the instance and install Pulp from.
repository: http://repos.fedorapeople.org/repos/pulp/pulp/beta/2.4

# The Openstack key pair to use. This tells Openstack what public key to authorize
# for the instance default user (usually 'cloud-user' or 'fedora').
keypair_name: sample_keypair_name

# The private key associated with the Openstack key pair.
private_key: path/to/private/key

# The distribution to use for the Pulp server and consumer. 'el6', 'fc20', etc.
distribution: el7

# The size (cpu, RAM, disk space) for each instance. See OS1 for other options.
flavor: m1.small

# The Openstack security group to use. This tells Openstack what network traffic
# is allowed to reach the machine. The default should normally be acceptable.
security_group: pulp

# Path the the cloud config to use when building instances. The default should normally be fine.
cloud_config: cloud-init/cloud-config.txt


# ==================
# Instance Structure
# ==================
#
# The 'structure' dictionary defines the instances to set up, and their relationships.
# A server instance should be at the root of this structure, and it can have a list of
# child instances. These children can be consumers or, once supported, server nodes.
# Each server node could itself have children.

structure:
    instance_name: demo-el7-pulp-server
    role: server
    flavor: m1.medium
    # A list of instances that are children to this instance. Currently, only consumers are supported
    children:
        - instance_name: demo-el7-pulp-consumer
          role: consumer
# An example of a second child
#       - instance_name: demo-el6-pulp-consumer
#         role: consumer
#         distribution: el6


# =========================
# Integration Test Instance
# =========================
#
# The 'pulp_tester' dictionary specifies configuration information for the machine 
# that runs the integration tests. Currently, the automation team uses Fedora 20 to
# run the tests. The tests require Fedora or RHEL7, and RHEL7 occasionally
# hangs while running the tests.

pulp_tester:
    distribution: fc20
    instance_name: pulp-tester
    role: tester
    # The automated tests expect an operating system name and version
    os_name: Fedora
    os_version: 20
    # The path to put the nosetests results
    tests_destination: nosetests.xml
    # The git branch to use when running the tests
    test_suite_branch: master

